frase = str(input('Digite uma frase: ')).upper().strip()
print('A letra A aparece {} vezes na frase'.format(frase.count('A')))
print('A letra E aparece {} vezes na frase'.format(frase.count('E')))
print('A letra I aparece {} vezes na frase'.format(frase.count('I')))
print('A primeira letra A apareceu na posicao {}'.format(frase.find('A')+1))
print('A primeira letra E apareceu na posicao {}'.format(frase.find('E')+1))
print('A primeira letra I apareceu na posicao {}'.format(frase.find('I')+1))
print('A primeira letra A apareceu na posicao {}'.format(frase.rfind('A')+1))
print('A primeira letra E apareceu na posicao {}'.format(frase.rfind('E')+1))
print('A primeira letra I apareceu na posicao {}'.format(frase.rfind('I')+1))